/*
 * generated by Xtext
 */
package arduinoml.validation

import org.eclipse.xtext.validation.Check
import arduinoml.AMLMachine

/**
 * Custom validation rules. 
 *
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
class AMLXValidator extends AbstractAMLXValidator {

	@Check
	def checkGreetingStartsWithCapital(AMLMachine m) {
		if (!m.start.name.equals("ybwb"))
			 warning("You better work bitch!!", m.start, m.start.eClass.getEStructuralFeature("name"));
	}
}