/*
 * generated by Xtext
 */
package arduinoml.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import arduinoml.ui.internal.AMLXActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class AMLXExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return AMLXActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return AMLXActivator.getInstance().getInjector(AMLXActivator.ARDUINOML_AMLX);
	}
	
}
