/**
 * generated by Xtext
 */
package arduinoml.validation;

import arduinoml.validation.AbstractAMLXValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class AMLXValidator extends AbstractAMLXValidator {
}
