/**
 * generated by Xtext
 */
package arduinoml.ui.contentassist;

import arduinoml.ui.contentassist.AbstractAMLXProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class AMLXProposalProvider extends AbstractAMLXProposalProvider {
}
