/*
* generated by Xtext
*/
package arduinoml.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import arduinoml.services.AMLXGrammarAccess;

public class AMLXParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private AMLXGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected arduinoml.parser.antlr.internal.InternalAMLXParser createParser(XtextTokenStream stream) {
		return new arduinoml.parser.antlr.internal.InternalAMLXParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Machine";
	}
	
	public AMLXGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(AMLXGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
