/*
 * generated by Xtext
 */
package arduinoml;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class AMLXRuntimeModule extends arduinoml.AbstractAMLXRuntimeModule {

}
