/*
* generated by Xtext
*/
package arduinoml;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class AMLXUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return arduinoml.ui.internal.AMLXActivator.getInstance().getInjector("arduinoml.AMLX");
	}
	
}
