/**
 * generated by Xtext
 */
package arduinoml.serializer;

import arduinoml.serializer.AbstractAMLXSyntacticSequencer;

@SuppressWarnings("all")
public class AMLXSyntacticSequencer extends AbstractAMLXSyntacticSequencer {
}
