/**
 * generated by Xtext
 */
package arduinoml.serializer;

import arduinoml.serializer.AbstractAMLXSemanticSequencer;

@SuppressWarnings("all")
public class AMLXSemanticSequencer extends AbstractAMLXSemanticSequencer {
}
