/*
 * generated by Xtext
 */
package arduinoml.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class AMLXUiModule extends arduinoml.ui.AbstractAMLXUiModule {
	public AMLXUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
